### PR TITLE
refactor: pull navbar at top and dynamically render

### PR DESCRIPTION
**Pull request by rvente**

### CODE REVIEW

**Review by muskankapoor — APPROVED** [review]
This looks good especially fixing the navbar
Please merge it at your will

**Comment by rvente** [comment]
Still stuck trying to figure out proxy stuff tho :(

**Comment by muskankapoor** [comment]
> Still stuck trying to figure out proxy stuff tho :(

Hmm, yes it was troubling us yesterday. cant believe the problem still persists. 
@shikdernyc  please let us know if you are able to give us insight into this issue?

**Comment by rvente** [comment]
We just got off a call. I'm attempting changes now.

**Comment by rvente** [comment]
Postponing this issue to another PR

**Pull request merged**
