### PR TITLE
Fix: Api proxy

### PR DESCRIPTION
**Pull request by rvente**

### CODE REVIEW

**Review by muskankapoor — APPROVED** [review]
This looks good to me! Please merge it
So removing prod fixed it?

**Comment by rvente** [comment]
Nah, I'm still deadlocked here.

**Comment by rvente** [comment]
Fixed: @muskankapoor

**Comment by muskankapoor** [comment]
> Fixed: @muskankapoor . Merge upon verification that it works for you https://deploy-preview-6--boring-lichterman-25372e.netlify.app/campuses

yesssss you did it! Excellent

**Pull request merged**
